version: '3.5'
services:
  fastapi_producer:
    build: .
    container_name: fastapi_producer
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/src
      - ./logs:/src/logs
    env_file:
      - .env
#    command: uvicorn main:app --reload --host 0.0.0.0 --port ${APP_PORT}

  rabbit1:
    image: library/rabbitmq:3.8.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbit1
    container_name: rabbit1
    restart: always
