FROM python:3.11.2-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir /app
WORKDIR /app

# pip & requirements
COPY requirements.txt requirements.txt
RUN python3 -m pip install --user --upgrade pip && \
    python3 -m pip install -r requirements.txt

CMD ["python", "consumer_a.py"]